### ISSUE TITLE
Processing time is not clear

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/PriorElicitation#3]
Processing time is represented by a greyed-out "round" number. There should be something more obvious, like a large spinning wheel taking up a significant part of the screen. Such code has been implemented on https://github.com/ocbe-uio/cellmigRation/commit/51e35de4c466fdc3a8f906f3a9d1109202b3656a.

**Comment by wleoncio** [comment]
Adding @OwenThomas's suggestion:

> Would it be maybe possible to make the buttons unclickable until the next simulation has fully loaded? It then would be strictly impossible to answer too quickly before the next simulation is showing.

So we basically have two possible solutions here:

- [x] Spinning wheel
- [x] Blocked-out buttons

Let's see what looks best (maybe both).

**Comment by wleoncio** [comment]
Hi, @OwenThomas! I've just deployed to https://ocbe.shinyapps.io/elicit/ and to the `dev` branch a proposal for a solution. I've added the loading elements mentioned above + some textual feedback. Things are not yet super explicit because there's still some delay between pressing the button and it being disabled, but at least we're making progress. Also, graying-out might not even trigger until later rounds, when there are more calculations to be made in the backend.

I appreciate any feedback in advance!

**Comment by wleoncio** [comment]
OK, so the current version deployed to https://ocbe.shinyapps.io/elicit/ seems to be working fine. On Pari-PRECIOUS, the buttons gray out and the icon changes into like a "stop sign" while the CPU is processing new plots (which normally takes less than a second in my experience). @OwenThomas, can you verify that solves this issue?

**Comment by OwenThomas** [comment]
Looks good, thank you!

**Comment by wleoncio** [comment]
Sweet!

Currently working on issue #5 and then #6, which I think will help you check if everything is working as it should. If you find any bugs, please feel free to submit a new Issue!
